### PR TITLE
netstandard2.0 and net45 support

### PR DESCRIPTION
**Pull request by windischb**
Added support for netstandard2.0 and net45
I have added a first small xunit Test...

### CODE REVIEW

**Comment by windischb** [comment]
For now have renamed Methodnames because Refit doesn't support Method overload for now..
I have also submitted a Pull Request in the Refit Support for Methodoverload Support, based on Reflection and matchin Parameters. -> https://github.com/paulcbetts/refit/pull/349
If the Pull Request in Refit wil be accepted and merged, i will change back the Method names.

**Comment by jlucansky** [comment]
Thank you for hard work. I noticed you also moved IQueryParameters from refit. In my fork, there is a special handling for all arguments of type IQueryParameters. I don't think it will work now without altering https://github.com/jlucansky/refit/blob/4c273b923376164c23b5e7b32efd017cdf754e2f/Refit/RequestBuilderImplementation.cs#L138

**Comment by windischb** [comment]
I have submitted a second Pull Request to Refit -> https://github.com/paulcbetts/refit/pull/355
If it will be merged, the IQueryParameter should not be needed anymore.

**Comment by nicojs** [comment]
@windischb the PR is merged. Can we update this PR? We would also like to use this client in .NET core projects.

Thanks for the hard work so far!

**Comment by secana** [comment]
Is there a status update for this pull request? I would like to use the library with .Net Standard, too.

**Comment by jlucansky** [comment]
There was still some issues with dynamic query parameters I finally figured out. Thank you for PR. We got rid of forked Refit and have .NET Standard 2.0 supported in [Release 2.0.0](https://github.com/jlucansky/Camunda.Api.Client/releases/tag/2.0.0)

**Pull request merged**
